CREATE TABLE T_CUSTOMER (
  ID DECIMAL(18,0) NOT NULL,
  NAME VARCHAR(32),
  NUMBER DECIMAL(10,0),
  RANGE CHAR(2),
  OPENING DATE,
  PRIMARY KEY (ID)
);

DROP FUNCTION IDENT;

CREATE FUNCTION IDENT (NUMBER DECIMAL(10,0), RANGE CHAR(2), OPENING DATE)
  RETURNS VARCHAR(64)
  LANGUAGE SQL
  CONTAINS SQL
  NO EXTERNAL ACTION
  DETERMINISTIC
  BEGIN
    IF OPENING IS NULL THEN
      RETURN NUMBER CONCAT '+' CONCAT RANGE CONCAT '+' CONCAT '-';
    ELSE
      RETURN NUMBER CONCAT '+' CONCAT RANGE CONCAT '+' CONCAT CHAR(OPENING);
    END IF;
  END;

SELECT ID, IDENT(NUMBER, RANGE, OPENING) AS IDENT FROM T_CUSTOMER;

DROP VIEW V_CUSTOMER;

CREATE VIEW V_CUSTOMER AS
SELECT ID, IDENT(NUMBER, RANGE, OPENING) AS IDENT FROM T_CUSTOMER;

SELECT * FROM V_CUSTOMER;

SELECT c.ID, c.NAME, c.NUMBER, c.RANGE, c.OPENING FROM T_CUSTOMER c, V_CUSTOMER v WHERE c.ID = v.ID
  AND (v.IDENT = '45271+03+05/13/2016' OR v.IDENT = '45271+03+-');

SELECT c.ID, c.NAME, c.NUMBER, c.RANGE, c.OPENING FROM T_CUSTOMER c, V_CUSTOMER v WHERE c.ID = v.ID
  AND (v.IDENT = '56351+17+11/21/2014' OR v.IDENT = '56351+17+-');