--
-- Create table T_MESSAGE and T_ROOM
--
CREATE TABLE T_ROOM (
  ID DECIMAL(18,0) NOT NULL,
  ROOM VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIMARY KEY (ID)
);

CREATE TABLE T_MESSAGE (
  ID DECIMAL(18,0) NOT NULL,
  NICK_ID DECIMAL(18,0) NOT NULL,
  ROOM_ID DECIMAL(18,0),
  TIMESTAMP TIMESTAMP,
  MESSAGE VARCHAR(2000),
  PRIMARY KEY (ID)
);

ALTER TABLE T_MESSAGE ADD FOREIGN KEY (NICK_ID) REFERENCES T_NICK_NAME (ID);
ALTER TABLE T_MESSAGE ADD FOREIGN KEY (ROOM_ID) REFERENCES T_ROOM (ID);

CREATE SEQUENCE SEQ_ID_ROOM START WITH 1000000 INCREMENT BY 10;
CREATE SEQUENCE SEQ_ID_MESSAGE START WITH 1000000 INCREMENT BY 10;
