--
--
--
INSERT INTO T_CUSTOMER (ID, NAME, NUMBER, RANGE, OPENING) VALUES (NEXT VALUE FOR SEQ_ID_CUSTOMER, 'John', 45271, '03', null );
INSERT INTO T_CUSTOMER (ID, NAME, NUMBER, RANGE, OPENING) VALUES (NEXT VALUE FOR SEQ_ID_CUSTOMER, 'Maggie', 45271, '03', '2016-05-13' );
INSERT INTO T_CUSTOMER (ID, NAME, NUMBER, RANGE, OPENING) VALUES (NEXT VALUE FOR SEQ_ID_CUSTOMER, 'Bill', 56351, '17', '2014-11-21' );
